frr defaults traditional
hostname r3
no ipv6 forwarding
!
interface eth1
 ip address 10.23.0.2/30
exit
!
interface eth2
 ip address 10.30.0.1/30
exit
!
interface lo
 ip address 13.0.0.1/24
exit
!
router bgp 300
 bgp router-id 3.3.3.3
 no bgp ebgp-requires-policy
 neighbor 10.23.0.1 remote-as 200
 !
 address-family ipv4 unicast
  network 13.0.0.0/24
  redistribute connected
  neighbor 10.23.0.1 activate
 exit-address-family
exit
!
ip route 13.0.0.50/32 10.30.0.2
!
end
