frr defaults traditional
hostname r4
no ipv6 forwarding
!
interface eth1
 ip address 10.14.0.2/30
exit
!
interface eth2
 ip address 10.40.0.1/30
exit
!
interface lo
 ip address 14.0.0.1/24
exit
!
router bgp 400
 bgp router-id 4.4.4.4
 no bgp ebgp-requires-policy
 no bgp network import-check
 neighbor 10.14.0.1 remote-as 100
 !
 address-family ipv4 unicast
  network 14.0.0.0/24
  redistribute connected
  neighbor 10.14.0.1 activate
 exit-address-family
exit
!
end
