no-resolv
no-hosts
log-queries
local-ttl=180
address=/www.victim.lab/14.0.0.66
address=/login.victim.lab/14.0.0.66
address=/mail.victim.lab/14.0.0.66
address=/api.victim.lab/14.0.0.66
address=/ns.victim.lab/14.0.0.66
