no-resolv
no-hosts
log-queries
local-ttl=300
address=/www.victim.lab/13.0.0.100
address=/login.victim.lab/13.0.0.80
address=/mail.victim.lab/13.0.0.25
address=/api.victim.lab/13.0.0.90
address=/ns.victim.lab/13.0.0.50
