frr version 9.1_git
frr defaults traditional
hostname r1
no ipv6 forwarding
service integrated-vtysh-config
!
interface eth1
 ip address 10.12.0.1/30
exit
!
interface eth2
 ip address 10.14.0.1/30
exit
!
interface eth3
 ip address 10.17.0.1/30
exit
!
interface lo
 ip address 11.0.0.1/24
exit
!
router bgp 100
 bgp router-id 1.1.1.1
 no bgp ebgp-requires-policy
 neighbor 10.12.0.2 remote-as 200
 neighbor 10.14.0.2 remote-as 400
 !
 address-family ipv4 unicast
  network 11.0.0.0/24
  redistribute connected
 exit-address-family
exit
!
