frr defaults traditional
hostname r5
no ipv6 forwarding
!
interface eth1
 ip address 10.25.0.2/30
exit
!
interface eth2
 ip address 10.56.0.1/30
exit
!
interface lo
 ip address 15.0.0.1/24
exit
!
router bgp 500
 bgp router-id 5.5.5.5
 no bgp ebgp-requires-policy
 neighbor 10.25.0.1 remote-as 200
 neighbor 10.56.0.2 remote-as 600
 !
 address-family ipv4 unicast
  network 15.0.0.0/24
  redistribute connected
  neighbor 10.25.0.1 activate
  neighbor 10.56.0.2 activate
 exit-address-family
exit
!
end
